version: 2.1
executors:
  test-executor:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

commands:
  run-target:
    description: "run a specific target"
    parameters:
      target:
        type: string
        default: ""
    steps:
      - checkout
      - run: python switchboard.py -t << parameters.target >>

jobs:
  hpat:
    executor: test-executor
    steps:
      - run-target:
          target: "hpat"
  umap:
    executor: test-executor
    steps:
      - run-target:
          target: "umap"
  librosa:
    executor: test-executor
    steps:
      - run-target:
          target: "librosa"
  clifford:
    executor: test-executor
    steps:
      - run-target:
          target: "clifford"
  awkward:
    executor: test-executor
    steps:
      - run-target:
          target: "awkward"
  sparse:
    executor: test-executor
    steps:
      - run-target:
          target: "sparse"
  fastparquet:
    executor: test-executor
    steps:
      - run-target:
          target: "fastparquet"
  pygbm:
    executor: test-executor
    steps:
      - run-target:
          target: "pygbm"


workflows:
  version: 2.1
  commit-integration-testing:
    jobs:
      # - hpat
      - umap
      - librosa
      - clifford
      - awkward
      - sparse
      - fastparquet
      - pygbm
  nightly-integration-testing:
    jobs:
      # - hpat
      - umap
      - librosa
      - clifford
      - awkward
      - sparse
      - fastparquet
      - pygbm
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                 - master
