version: 2.1
executors:
  test-executor:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

commands:
  run-target:
    description: "run a specific target"
    parameters:
      target:
        type: string
        default: ""
    steps:
      - checkout
      - run: sudo pip install --upgrade pip==21.0.1
      - run: sudo pip install packaging
      - run: sudo pip install git+https://github.com/numba/texasbbq
      - run:
          command: python switchboard.py -t << parameters.target >>
          no_output_timeout: 42m

jobs:
  hpat:
    executor: test-executor
    steps:
      - run-target:
          target: "hpat"
  umap:
    executor: test-executor
    steps:
      - run-target:
          target: "umap"
  librosa:
    executor: test-executor
    steps:
      - run: sudo apt update && sudo apt install libsamplerate0 libsndfile1
      - run-target:
          target: "librosa"
  clifford:
    executor: test-executor
    steps:
      - run-target:
          target: "clifford"
  awkward:
    executor: test-executor
    steps:
      - run-target:
          target: "awkward"
  sparse:
    executor: test-executor
    steps:
      - run-target:
          target: "sparse"
  fastparquet:
    executor: test-executor
    steps:
      - run-target:
          target: "fastparquet"
  datashader:
    executor: test-executor
    steps:
      - run-target:
          target: "datashader"
  pandas:
    executor: test-executor
    steps:
      - run-target:
          target: "pandas"
  tardis:
    executor: test-executor
    steps:
      - run-target:
          target: "tardis"
  poliastro:
    executor: test-executor
    steps:
      - run-target:
          target: "poliastro"
  numba-dppy:
    executor: test-executor
    steps:
      - run-target:
          target: "numba-dppy"


workflows:
  version: 2.1
  commit-integration-testing:
    jobs:
      - umap
      - librosa
      - clifford
      - awkward
      - sparse
      - fastparquet
      - datashader
      - pandas
      - tardis
      - poliastro
      - numba-dppy
  nightly-integration-testing:
    jobs:
      - umap
      - librosa
      - clifford
      - awkward
      - sparse
      - fastparquet
      - datashader
      - pandas
      - tardis
      - poliastro
      - numba-dppy
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                 - master
